# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "BFAJoTbMBHH8hC7K/k76bD9hPweu2BVxVVxJH/9hRj1n+lz0qUMKqpMS/T4Yo0gePxedMJ5Z34YLzEm6hKaS7f8e/8z0xYZOR2CaeuNEiLD1J9FaP/8PwOIjxFl5mo4kAFRCv5QzvuI/O93P7FQPUvMxuEwM32CKP9lP9cBDPbt3tAhBhrN9IxL8zG9ENu+0Zsix/8lmuiNb07jyFmcpqHyqWAnkLRRnOR2kboweuPZpsbh1sPREyVuwJFEH7+Cn8T4YwqvljPqXFvjysmRpK29wZz/G7ltd0eZ51+PPliF5czdEtTQspth6eU657Hnx0lbrT0tK+tEiHvJmEIeHzD056boRfHgWXPqSc8gJ6upqaUWugCxl4c5SvL/gz55dZg2edNaMrdR4y1Da775avLx0C5I6tdk/j1KwOK8Ea1fFiSv5636zZUnqjjtwN4uRXNDaL5IVXhCf+Wj1kwNn58KFksk1wOmqNvZEUbN6ll0f91QgDVEYCwTMYijeQZ8BgdIcH+PjocvAt7npgA31fdEVzhiiLm1wKophO9Nr21ph8/SCk7Sngh8jcx1hGE6GgHh52mjx9RyNhVRGkIwttn8adzVnbxQwdA33FPulzMTijMe+6SHSKygDvnBzh+TOo+ZfYSuGSS++Cgp30tNxijnlcWdBrSF6h6hmC4jy5PU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
