travis:
  secure:
    BINSTAR_TOKEN: gGK8jE86303srLEMy1oMtPqndK4rd+kCRkEVNxyssV/82mNSb2aM0GGCZA34PhFI6BU830P0TjJA2R2YzH4MGWXrRb8kEaluAx7UhTBQJpsY/0shflSsf6zblbozU1wlEqnp1UAuc6wAHWSrlmg8a5prOZxtNACrqFPV1fUpVOJ3cKnIrPODV2eDepYoJKPlvJigmqKvUaYMgSuBBW+XpjQOwMS2YEQ42HiO6II8ulzQQPYWqsKhgGlOb1ZGn/WN27qVyhq6OL2Yg6RvhQQ1bQm8Td3YBmty+dntBprG4vT0Iy/7g6+Gf7qxA7sod8sGx7KRwft23EIr1aH4hD6U5/puZVt9Nx1gIuyU6Idbq11FeCU3L0ObrsAzDFT5q6lX+v0Gxqw9c3SDwhPdEJrnfPTF5kdnf/3lXpb5jy6S4yAK4N4f5amjOg2j8UexyXsBZ7/lXmUfAH4DiE86X4BIGmoEYe+4OVRe5uNRB9AI9a/NMUkCjEFwmk/nFAVYGlKdWgYnfrvQaYtTY5aChaIi/J/P/cA3W1oIdW/s18hnVyfEV0AvMfhLZqKjr/kuQitMztAq+D5CLsVWYbQa4Rtj9hNYPZ2xC1FrUuq6sTrrYObiq8TYsODXFu4ZFYsyw8PUwXhXnllpEbNh9rv1sdUl/a3zOLR7FOMhB0BsIFz5h94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
