travis:
  secure:
    BINSTAR_TOKEN: jDOmtD3Qh7Pevsi10wS5hhThqjE76rjUwNR+NYgAh4ogbnceMBHCCWWIe3kwv1X0hiiMYfKwW5ifYCQWlZpCiDwobX+QD2A0jGQFX0S/3sDXF9BkfukZ8R9KlhDStPimHY0Rw89De7CAc0HmADKMejMKvGUIdDdVuMLpz4oKQlZoq3ITRBBT7rNkNjwspQfkg1MFXW91tIVmoPb7mh7D17Cj6ss9bciU4v+pgVsRNxX+GDdkKrtiIhAyN9czqYEZ7AX77R4TPM3y7PNBkhv0RPcoxDOiQC62WiS8FVeZWhGmGdKmrpTQ8wSidLYCwGEuw0PE52S7bSzgaDl2X3bk9MtNuYmJXazGqwgey/sooG2eBnwhG9rEg5TDoTFaAKZVSXw5MqlPEPHkZykk4ifSt8ASphRM/ol9QoE3LZLkBSahh3tiqF8S7M39QOPhjXis0HissB2oDlx9TQrl1/rtkSjdk7Y2TGV24NEvO+UyvEolSrsHrrQ8AXc+Z9IAX9FVkg4q3rqexf8y7zcKE/tAx4hKkrn+YPtE6m+EUjSnpex8l5NQ3clsja8ljfED3H4Lwqx0xFJix3gxwoHQE9G3fjcK4YuA8vzuv97dubMRiU0mL9BppnBNdyC9cN7dB1K3jOFpGVazvxYkHDFPXeoM3JqX1gwlhjEreRG+m7BRiAU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
