travis:
  secure:
    BINSTAR_TOKEN: MsGzixs55QiS9z6XTh60Yv9XnftMhfJIcuMmrszvvCF28xtE95xmZfuwC/sCI5W6V8NzWuaXTiGLqfXoxaeGEZfinp5lTT8f23KylK9chZ7sYtyv0DjslrBPBTUmt9kbr3XdeubO0wNafsmKdkk0+EgpTXipPrhvHwSWXY7OwRAeRq2yLlMSHx0YpaGt+jENb0DLTDO4kMbPXMC1mosju6ZgdjBGCuuRMKulvyOjXbsi+NDnOelrUUvnvOrvd/S1M/a9DZYtaN7qwJfz3bL2l4iqMf3sQXrCG3Uw7x3QW9k2yf7NV6Mh2pUKs9yCA4xDK33tYROGauczY9OyFmo6bGUs72at8RLD7c1v6sSq+lmtv3EY2bvTKak0cndtgInjZnCA6faibe0IuVjDeu3TxllKJ8XxEc5dzFMEo4GakK81q2jHIAbLo/XuIjrAkfqVOfYbd3gdrusQH6Nw+XcIi70cqr65KrEcj3crhw9GwZIyjSZFc+ssdbqm90wX7Oj2uid9eLvhEhdh1GA/DZ4X5ys3++YJ+gUt4I9rH1Eu84Le8PkUM2478zf35C63/kO5Cxc+ZXwCzSfYBKmJKFfp0z3cbfrUN0vTm5G/VBeGU6v7xyj4ojhVzb5+MvpJROhPN5XwjwlmFH0ZmyHTYew1fL+9xrR+Z/i9J1vpX8steME=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
